{
 "title": "Traffic (ClickHouse)",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Instant traffic",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeInterval(time_flow_start) as \"time\", time_flow_start, sum(bytes) as bytes FROM \"default\".\"flows_raw_view\" WHERE ( time >= $__fromTime AND time <= $__toTime ) GROUP BY time_flow_start, time ORDER BY time ASC"
    }
   ]
  },
  {
   "title": "Top source IPs",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeInterval(time_flow_start) as \"time\", time_flow_start, src_addr, sum(bytes) as bytes FROM \"default\".\"flows_raw_view\" WHERE ( time >= $__fromTime AND time <= $__toTime ) GROUP BY time_flow_start, src_addr, time ORDER BY time ASC"
    }
   ]
  },
  {
   "title": "Top source ports",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeInterval(time_flow_start) as \"time\", time_flow_start, src_port, sum(bytes) as bytes FROM \"default\".\"flows_raw_view\" WHERE ( time >= $__fromTime AND time <= $__toTime ) GROUP BY time_flow_start, src_port, time ORDER BY time ASC, bytes DESC"
    }
   ]
  },
  {
   "title": "Top destination IPs",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeInterval(time_flow_start) as \"time\", time_flow_start, dst_addr, sum(bytes) as bytes FROM \"default\".\"flows_raw_view\" WHERE ( time >= $__fromTime AND time <= $__toTime ) GROUP BY time_flow_start, dst_addr, time ORDER BY time ASC"
    }
   ]
  },
  {
   "title": "Top destination ports",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeInterval(time_flow_start) as \"time\", time_flow_start, src_port, sum(bytes) as bytes FROM \"default\".\"flows_raw_view\" WHERE ( time >= $__fromTime AND time <= $__toTime ) GROUP BY time_flow_start, src_port, time ORDER BY time ASC"
    }
   ]
  }
 ]
}